---
network:
  # Worker IPs are simply incremented from the control IP.
  control_ip: 192.168.10.150
  dns_servers:
    - 8.8.8.8
    - 192.168.10.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 4
    memory: 8192
  workers:
    count: 3
    cpu: 12
    memory: 65536
software:
  box: generic/ubuntu2004
  kubernetes: 1.31
  os: xUbuntu_20.04
